### ISSUE TITLE
Do you really need numpy as build dependency?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/slitlessutils#65]
At a glance, I don't see any C-extension, and you are publishing only universal wheel on PyPI. So maybe can remove numpy as *build* dependency.

https://github.com/spacetelescope/slitlessutils/blob/8ecfe054cfcfe0b94941d231605872de8e3ab781/pyproject.toml#L71

**Comment by larrybradley** [comment]
Yep, that's not needed.  Thanks!
